// ============================================================
// SQUARE CHECKOUT INTEGRATION
// For each item, create a Payment Link in the Square Dashboard
// (Payment Links > Create > Sell an item — pick the item from
// the library so sizes/variations carry over). Use a
// *subscription* link for monthly Club memberships.
// Paste each URL between the quotes — buttons go live instantly.
// Items with no link show a friendly "call or visit" message.
// ============================================================
const PAYMENT_LINKS = {
  // ----- Tanning packages & memberships -----
  "l2-single": "",     // Level 2 — single visit $12
  "l2-five": "",       // Level 2 — five visits $50
  "l2-ten": "",        // Level 2 — ten visits $80
  "l2-150": "",        // Level 2 — 150 minutes $100
  "l2-300": "",        // Level 2 — 300 minutes $120
  "l2-month": "",      // Level 2 — one-month unlimited $65
  "l2-club": "",       // Level 2 — Club Tan $55/mo (subscription)
  "l3-single": "",     // Level 3 — single visit $15
  "l3-five": "",       // Level 3 — five visits $60
  "l3-ten": "",        // Level 3 — ten visits $100
  "l3-150": "",        // Level 3 — 150 minutes $110
  "l3-300": "",        // Level 3 — 300 minutes $150
  "l3-month": "",      // Level 3 — one-month unlimited $75
  "l3-club": "",       // Level 3 — Club Tan $65/mo (subscription)
  "rl-single": "",     // Red light — single $12
  "rl-five": "",       // Red light — five visits $50
  "rl-ten": "",        // Red light — ten visits $80
  "rl-month": "",      // Red light — one-month unlimited $75
  "spray-single": "",  // Spray tan session $30
  "spray-club": "",    // Club Spray $65/mo (subscription)
  "week-any": "",      // Straight-week tanning $35
  "family-add": "",    // Add family member to any package $30
  // ----- Boutique & products (from Square item library) -----
  "accity-blanket": "", // Accity blanket ($58)
  "almond-beige-flat-clip-large": "", // Almond Beige flat clip large ($14.99)
  "almond-beige-flat-clip-medium": "", // Almond Beige flat clip medium ($12.99)
  "black-matte-hair-ties-large-3-pk": "", // Black Matte hair ties large 3 pk ($9.99)
  "black-sparkle-cosmetic-bag": "", // Black sparkle cosmetic bag ($10)
  "body-restore-shower-steamer-aromatherapy-tube-pack-of-6": "", // Body Restore Shower Steamer Aromatherapy Tube Pack of 6 ($24)
  "booties": "", // Booties ($35)
  "cala-12-piece-precision-razors-set-hair-removal": "", // CALA 12 Piece Precision Razors Set Hair Removal ($15)
  "cala-beauty-reset-satin-pillowcase-2pcs": "", // CALA BEAUTY RESET SATIN PILLOWCASE 2pcs ($24)
  "cala-makeup-removal-microfiber-cleansing-facial-towel-3pk": "", // CALA Makeup Removal Microfiber Cleansing Facial Towel (3PK) ($15)
  "cala-spa-bubble-puffy-headband-and-wristband-set-pink-green": "", // CALA Spa Bubble Puffy Headband and Wristband Set Pink Green ($15)
  "cala-wet-n-dry-detangling-hair-brush": "", // CALA Wet-n-Dry Detangling Hair Brush ($15)
  "coconut-white-hair-ties-large-3-pk": "", // Coconut White hair ties large 3 pk ($9.99)
  "coconut-white-hair-ties-small-3-pk": "", // Coconut White hair ties small 3 pk ($7.99)
  "crystal-clear-hair-ties-small-3-pk": "", // Crystal Clear hair ties small 3 pk ($7.99)
  "elephant-falls-flat-clip-green": "", // Elephant Falls flat clip green ($14.99)
  "fuschia-dream-flat-clip-pink": "", // Fuschia Dream flat clip pink ($14.99)
  "game-day-purse": "", // Game Day purse ($30)
  "game-day-strap": "", // Game Day strap ($36)
  "gold-cross-pendant-pearl-triple-layer-chain-necklace": "", // Gold Cross Pendant Pearl Triple Layer Chain Necklace ($15)
  "jet-black-claw-clip-large": "", // Jet Black claw clip large ($14.99)
  "lulumac-beaded-wristlet": "", // LuluMac beaded wristlet ($13)
  "lulumac-blanket-blue": "", // LuluMac blanket blue ($45)
  "lulumac-bracelet": "", // LuluMac bracelet ($20–$25)
  "lulumac-bracelet-set-blue-red": "", // LuluMac bracelet set blue/red ($25)
  "lulumac-canvas-tote-black-black-logo": "", // LuluMac canvas tote black/black logo ($20)
  "lulumac-hair-clip-black-polka-dot": "", // Lulumac hair clip black polka dot ($10)
  "lulumac-hairclip-camo": "", // LuluMac Hairclip camo ($10)
  "lulumac-hat": "", // LuluMac hat ($15–$19)
  "lulumac-hat-lake": "", // LuluMac hat Lake ($19)
  "lulumac-hat-lake-pink": "", // LuluMac hat Lake pink ($19)
  "lulumac-keychain": "", // LuluMac keychain ($17)
  "lulumac-koozie": "", // LuLuMac koozie ($4)
  "lulumac-leopard-print-tote": "", // Lulumac leopard print tote ($30)
  "lulumac-necklace-mixed-silver-gold": "", // LuluMac Necklace mixed silver/gold ($15)
  "lulumac-plush-blanket": "", // LuluMac plush blanket ($45)
  "lulumac-polka-dot-tote-blue": "", // LuLuMac polka dot tote blue ($30)
  "lulumac-puffer-tote-leopard": "", // LuLumac puffer tote leopard ($55)
  "lulumac-puffer-tote-mint": "", // LuLumac puffer tote mint ($55)
  "lulumac-raincoat-blue-stripe": "", // Lulumac raincoat blue stripe ($55)
  "lulumac-tote": "", // LuluMac tote ($20)
  "lulumac-tumbler": "", // LuluMac tumbler ($25)
  "no-doubt-booties": "", // No Doubt booties ($40)
  "pearly-pink-claw-clip-large": "", // Pearly pink claw clip large ($14.99)
  "pearly-pink-flat-clip-large": "", // Pearly Pink flat clip large ($14.99)
  "pearly-pink-flat-clip-medium": "", // Pearly Pink flat clip medium ($12.99)
  "rose-water-pink-hair-ties-small-3-pk": "", // Rose Water Pink hair ties small 3 pk ($7.99)
  "southern-limit-hat": "", // Southern Limit hat ($29)
  "stuff-cosmetic-bag": "", // Stuff cosmetic bag ($12)
  "technicolor-dreams-hair-ties-lg-sm-combo": "", // Technicolor Dreams hair ties lg/sm combo ($14.99)
  "totally-turquoise-hair-ties-large-3-pk": "", // Totally Turquoise hair ties large 3 pk ($9.99)
  "tote-bag-animal-print": "", // Tote bag - animal print ($24)
  "tote-bag-black-grey-or-khaki": "", // Tote bag - black, grey or khaki ($15)
  "trucker-hat": "", // Trucker hat ($30)
  "tumbler-40-oz-animal-print": "", // Tumbler 40 oz animal print ($30)
  "tumbler-40-oz-game-day": "", // Tumbler 40 oz Game Day ($35)
  "washed-denim-blue-hair-ties-small-3-pk": "", // Washed Denim blue hair ties small 3 pk ($7.99)
  "black-ruffle-sleeve-top": "", // Black ruffle sleeve top ($15)
  "blue-cotton-shorts": "", // Blue cotton shorts ($22)
  "blue-solid-sweatshirt": "", // Blue solid sweatshirt ($20)
  "bucketlist-contrast-sweatshirt": "", // BucketList contrast sweatshirt ($45)
  "dear-lover-graphic-t-shirt": "", // Dear Lover graphic t shirt ($15)
  "drop-shoulder-mock-neck-usa-flag-graphic-sweater": "", // DROP SHOULDER MOCK NECK 'USA FLAG' GRAPHIC SWEATER ($42)
  "gold-layered-necklace-with-heart-pendant-and-pearl-accents": "", // Gold Layered Necklace with Heart Pendant and Pearl Accents ($12)
  "hemp-nation-tan-extender-2": "", // Hemp nation tan extender ($22)
  "jet-black-flat-clip-large": "", // Jet Black flat clip large ($14.99)
  "jet-black-flat-clip-medium": "", // Jet Black flat clip medium ($12.99)
  "light-pink-strip-puff-sleeve": "", // Light pink strip puff sleeve ($18)
  "lulumac-sweatshirt-mint-coral": "", // LuluMac sweatshirt mint/coral ($49)
  "nashville-t-shirt": "", // Nashville t-shirt ($15)
  "one-hot-mama": "", // One hot mama ($65)
  "pink-raw-hem-top": "", // Pink raw hem top ($20)
  "sea-it-to-believe-it": "", // Sea it to believe it ($40)
  "sunglasses": "", // Sunglasses ($12)
  "sunshine-superstar": "", // Sunshine superstar ($60)
  "aapparella-animal-print-top": "", // Aapparella animal print top ($26)
  "aapparella-blue-stripe-skort-set": "", // Aapparella blue stripe skort set ($45)
  "aapparella-stripe-short-set-yellow-blue": "", // Aapparella stripe short set yellow/blue ($48)
  "aapparella-stripe-top-accent-trim": "", // Aapparella stripe top accent trim ($24)
  "alabama-hair-ties-large-3-pk": "", // Alabama hair ties large 3 pk ($9.99)
  "alabama-mock-neck-reversible": "", // Alabama mock neck reversible ($46)
  "alabama-t-shirt": "", // Alabama t shirt ($32)
  "back-bow-detail-sleeveless-striped-sweater-top": "", // BACK BOW DETAIL SLEEVELESS STRIPED SWEATER TOP ($46)
  "bama-tan-shirts": "", // Bama Tan shirts ($30)
  "bama-tan-t-shirt": "", // Bama Tan t shirt ($30)
  "black-contrast-trim-sleeveless-top-and-shorts-set": "", // Black Contrast Trim Sleeveless Top and Shorts Set ($35)
  "black-swimsuit": "", // Black swimsuit ($18–$20)
  "blue-rodeo-t-shirt": "", // Blue rodeo t-shirt ($18)
  "blue-stripe-short-set": "", // Blue stripe short set ($25)
  "blue-striped-dress": "", // Blue striped dress ($25)
  "bralette": "", // Bralette ($22)
  "bucketlist-alabama-top": "", // BucketList Alabama top ($36)
  "bucketlist-black-stripe-top": "", // BucketList black stripe top ($34)
  "by-together-green-stripe-sweater": "", // By Together green stripe sweater ($40)
  "by-together-navy-white-top": "", // By Together navy/white top ($49)
  "camo-print-short-sleeve-top-and-shorts-lounge-set-s-xl": "", // Camo Print Short Sleeve Top and Shorts Lounge Set (S-XL) ($43)
  "camo-print-tee-and-wide-leg-pants-two-piece-set": "", // Camo Print Tee and Wide Leg Pants Two Piece Set ($48)
  "color-block-notch-neck-short-sleeve-knit-top": "", // Color Block Notch Neck Short Sleeve Knit Top ($28)
  "colorblock-drop-shoulder-t-shirt-and-skort-2pcs-set-s-xl": "", // Colorblock Drop Shoulder T Shirt and Skort 2Pcs Set (S-XL) ($55)
  "contrast-trim-knit-top-short-sleeve-casual-sweater": "", // Contrast Trim Knit Top Short Sleeve Casual Sweater ($30)
  "dear-lover-khaki-shorts": "", // Dear Lover khaki shorts ($22)
  "dear-lover-pink-leopard-print": "", // Dear Lover pink leopard print ($15)
  "dear-lover-pink-raw-hem-top": "", // Dear Lover pink raw hem top ($20)
  "dear-lover-pink-white-stripe-top": "", // Dear Lover pink white stripe top ($18)
  "dear-lover-plus-size-denim-shorts": "", // Dear Lover plus size denim shorts ($25)
  "dear-lover-plus-size-leopard-print-top": "", // Dear Lover plus size leopard print top ($18)
  "dear-lover-ruffle-sleeve-top-black": "", // Dear Lover ruffle sleeve top black ($15)
  "dl-black-wide-leg-jeans": "", // DL black wide leg jeans ($32)
  "dl-black-cream-dress-bow-detail-back": "", // DL black/cream dress bow detail back ($34)
  "dl-blue-long-sleeve-color-block-shirt": "", // DL blue long sleeve color block shirt ($24)
  "dl-blue-ribbed-short-sleeve-top": "", // DL blue ribbed short sleeve top ($18)
  "dl-brown-shacket": "", // DL Brown Shacket ($35)
  "dl-brown-blue-stripe-long-sleeve-top": "", // DL brown/blue stripe long sleeve top ($26)
  "dl-brown-leopard-long-sleeve-top": "", // DL brown/leopard long sleeve top ($26)
  "dl-cream-sweater-bow-detail-back": "", // DL cream sweater bow detail back ($32)
  "dl-cream-black-bow-top": "", // DL cream/black bow top ($24)
  "dl-distressed-denim-shorts": "", // DL distressed denim shorts ($25)
  "dl-distressed-skinny-jeans": "", // DL distressed skinny jeans ($30)
  "dl-double-button-high-rise-jeans": "", // DL double button high rise jeans ($32)
  "dl-linen-blue-shorts": "", // DL linen blue shorts ($22)
  "dl-med-wash-high-waist-jeans": "", // DL med wash high waist jeans ($32)
  "dl-pink-color-block-top": "", // DL pink color block top ($20)
  "dl-spooky-t-shirt": "", // DL spooky t shirt ($20)
  "dz-black-crop-sweater": "", // DZ Black Crop Sweater ($28)
  "dz-black-cream-sweater": "", // DZ Black/Cream Sweater ($30)
  "dz-dolman-top-green": "", // DZ Dolman Top Green ($22)
  "dz-dolman-top-navy": "", // DZ Dolman Top Navy ($22)
  "dz-hoodie-top": "", // DZ Hoodie Top ($20)
  "dz-joggers": "", // DZ Joggers ($25)
  "dz-pink-crop-top": "", // DZ Pink Crop Top ($16)
  "dz-purple-sweater": "", // DZ Purple Sweater ($32)
  "floral-bow-detail-dress": "", // Floral bow detail dress ($58)
  "hem-thread-blue-white-shirt": "", // Hem&thread blue/white shirt ($45)
  "hem-thread-pink-white-shirt": "", // Hem&thread pink/white shirt ($45)
  "just-black-denim-light-wash-denim-shorts": "", // Just Black Denim light wash denim shorts ($32)
  "just-black-denim-white-jeans": "", // Just Black Denim white jeans ($50)
  "just-black-denim-white-shorts": "", // Just Black Denim white shorts ($32)
  "las-contrast-striped-notched-puff-sleeve-mini-dress-s-xl": "", // LAS Contrast Striped Notched Puff Sleeve Mini Dress (S-XL) ($45)
  "las-polka-dot-halter-tank-drawstring-shorts-set-s-xl": "", // LAS Polka Dot Halter Tank Drawstring Shorts Set (S-XL) ($38)
  "las-polka-dot-printed-tee-and-shorts-set-s-xl": "", // LAS Polka Dot Printed Tee and Shorts Set (S-XL) ($49.5)
  "las-stripe-contrast-trim-boxy-terry-short-set-s-xl": "", // LAS Stripe Contrast Trim Boxy Terry Short Set (S-XL) ($52)
  "las-stripe-dolman-tee-drawstring-skort-2pcs-set-s-xl": "", // LAS Stripe Dolman Tee Drawstring Skort 2pcs Set (S-XL) ($52–$56)
  "las-stripe-raised-rib-tee-drawstring-2pcs-short-set-s-xl": "", // LAS Stripe Raised Rib Tee Drawstring 2pcs Short Set (S-XL) ($47)
  "las-stripe-scallop-hem-top-shorts-set-s-xl": "", // LAS Stripe Scallop Hem Top Shorts Set (S-XL) ($49.5)
  "ldc-white-camo-set": "", // LDC white camo set ($48)
  "le-lis-round-neck-sweater-top": "", // Le Lis round neck sweater top ($46)
  "lovesoft-black-white-shacket": "", // LoveSoft black/white shacket ($38)
  "lovesoft-color-block-crewneck-top": "", // LoveSoft color block crewneck top ($26)
  "lovesoft-loose-fit-pullover": "", // LoveSoft loose fit pullover ($22)
  "ls-society-stripe-set-pink-yellow": "", // LS Society stripe set pink/yellow ($52)
  "lulu-leggings": "", // Lulu leggings ($45)
  "lulu-shirts": "", // Lulu shirts ($35)
  "lulu-shorts": "", // Lulu shorts ($35)
  "lulu-sports-bra": "", // Lulu sports bra ($30)
  "lulumac-boxer-light-camo": "", // LuluMac boxer light camo ($25)
  "lulumac-boxer-short-camo": "", // LuluMac boxer short camo ($25)
  "lulumac-boxer-short-leopard": "", // LuluMac boxer short leopard ($25)
  "lulumac-boxer-shorts-navy-gingham": "", // LuluMac boxer shorts navy/gingham ($25)
  "lulumac-cc-tank-blossom": "", // LuluMac CC tank Blossom ($33–$37)
  "lulumac-cc-tank-chalky-mint": "", // LuluMac CC tank chalky mint ($33)
  "lulumac-cc-tank-chambray": "", // LuluMac CC tank chambray ($33)
  "lulumac-joggers": "", // LuluMac joggers ($40)
  "lulumac-kids-baby-doll-top-lavender": "", // LuluMac kids baby doll top lavender ($27)
  "lulumac-kids-baby-doll-top-light-blue": "", // LuLuMac kids baby doll top light blue ($27)
  "lulumac-kids-camo-t-shirt-butter": "", // LuluMac kids camo T-shirt butter ($33)
  "lulumac-kids-camo-t-shirt-light-blue": "", // LuLuMac kids camo T-shirt light blue ($33)
  "lulumac-kids-camo-t-shirt-pink": "", // Lulumac kids camo T-shirt pink ($33)
  "lulumac-kids-polka-t-shirt-mint": "", // Lulumac kids polka t shirt mint ($29)
  "lulumac-kids-sweatshirt-mono-blue": "", // Lulumac kids sweatshirt mono blue ($53)
  "lulumac-kids-sweatshirt-mono-pink": "", // Lulumac kids sweatshirt mono pink ($53)
  "lulumac-kids-t-shirt-green-orange-stripe": "", // Lulumac kids t shirt green/orange stripe ($28)
  "lulumac-kids-t-shirt-leopard-pink": "", // Lulumac kids t shirt leopard/pink ($28)
  "lulumac-kids-tshirt-chambray-polkadot": "", // Lulumac kids tshirt chambray polkadot ($29)
  "lulumac-leggings": "", // LuluMac leggings ($40)
  "lulumac-leggings-black": "", // LuluMac leggings black ($40)
  "lulumac-leggings-camo": "", // LuLuMac leggings camo ($45)
  "lulumac-leopard-waffle-pants": "", // LuluMac leopard waffle pants ($49)
  "lulumac-leopard-waffle-pop-top": "", // LuluMac leopard waffle pop top ($49)
  "lulumac-og-short-mint": "", // LuluMac OG short mint ($20)
  "lulumac-og-short-navy": "", // LuluMac OG short navy ($20)
  "lulumac-pjs": "", // LuluMac pjs ($59)
  "lulumac-pjs-cherries": "", // LuluMac pjs cherries ($59)
  "lulumac-polka-dot-boxer-short-hot-pink": "", // LuLuMac polka dot boxer short hot pink ($25)
  "lulumac-polka-dot-boxer-short-navy": "", // LuLuMac polka dot boxer short navy ($25)
  "lulumac-polka-dot-t-shirt-flo-blue": "", // LuluMac polka dot t shirt Flo blue ($31–$35)
  "lulumac-polka-dot-tshirt-pink": "", // LuLuMac polka dot tshirt pink ($31–$35)
  "lulumac-polka-dot-tshirt-yellow": "", // LuLuMac polka dot tshirt yellow ($31–$35)
  "lulumac-raincoat": "", // LuluMac raincoat ($55)
  "lulumac-shorts": "", // LuluMac shorts ($20–$22)
  "lulumac-shorts-bubblegum": "", // LuLuMac shorts bubblegum ($20)
  "lulumac-shorts-grey": "", // LuluMac shorts grey ($20)
  "lulumac-shorts-hot-pink": "", // LuLuMac shorts hot pink ($20)
  "lulumac-shorts-red": "", // LuLumac shorts red ($20)
  "lulumac-solid-babydoll-top": "", // LuluMac solid babydoll top ($29)
  "lulumac-stripe-society-babydoll-top": "", // LuluMac stripe society babydoll top ($35–$37)
  "lulumac-stripe-society-shorts": "", // LuluMac stripe society shorts ($29–$31)
  "lulumac-striped-long-sleeve-red-pink": "", // LuluMac striped long sleeve red/pink ($49)
  "lulumac-striped-short-sleeve-red-pink": "", // LuLumac striped short sleeve red/pink ($35)
  "lulumac-striped-shorts-red-pink": "", // LuLumac striped shorts red/pink ($29)
  "lulumac-striped-society-pants-pink": "", // LuluMac striped society pants pink ($49)
  "lulumac-sweatshirt-brown-camo": "", // LuluMac sweatshirt brown/camo ($55)
  "lulumac-sweatshirt-butter-camo": "", // LuluMac sweatshirt butter/camo ($55–$57)
  "lulumac-sweatshirt-butter-light-blue": "", // LuluMac sweatshirt butter/light blue ($49)
  "lulumac-sweatshirt-chartreuse-dark-blue": "", // LuluMac sweatshirt chartreuse/dark blue ($49–$51)
  "lulumac-sweatshirt-coral-mint": "", // Lulumac sweatshirt coral/mint ($49)
  "lulumac-sweatshirt-crimson-houndstooth": "", // Lulumac sweatshirt crimson/houndstooth ($55–$57)
  "lulumac-sweatshirt-green-camo": "", // LuluMac sweatshirt green/camo ($55–$57)
  "lulumac-sweatshirt-leopard-pink": "", // LuLumac sweatshirt leopard/pink ($55)
  "lulumac-sweatshirt-light-blue-mono": "", // LuluMac sweatshirt light blue mono ($55)
  "lulumac-sweatshirt-light-blue-camo": "", // LuluMac sweatshirt light blue/camo ($55–$57)
  "lulumac-sweatshirt-light-blue-navy": "", // LuluMac sweatshirt light blue/navy ($49)
  "lulumac-sweatshirt-light-pink-pink-puff": "", // LuluMac sweatshirt light pink/pink puff ($49)
  "lulumac-sweatshirt-lt-blue-leopard": "", // LuluMac sweatshirt lt blue/leopard ($55)
  "lulumac-sweatshirt-lt-blue-navy-stripe": "", // LuluMac sweatshirt lt blue/navy stripe ($59)
  "lulumac-sweatshirt-lt-pink-hot-pink-stripe": "", // LuluMac sweatshirt Lt pink/hot pink stripe ($59)
  "lulumac-sweatshirt-mono-dark-grey": "", // LuluMac sweatshirt mono dark grey ($55)
  "lulumac-sweatshirt-navy-lt-blue-stripe": "", // LuluMac sweatshirt navy/lt blue stripe ($59)
  "lulumac-sweatshirt-pink-mono": "", // LuluMac sweatshirt pink mono ($55)
  "lulumac-sweatshirt-pink-light-pink-puff": "", // LuluMac sweatshirt pink/light pink puff ($49)
  "lulumac-sweatshirt-pink-red-gingham-stitch": "", // LuluMac sweatshirt pink/red gingham stitch ($55)
  "lulumac-sweatshirt-stripe-society-butter-lavender": "", // LuluMac sweatshirt stripe society butter/lavender ($59–$61)
  "lulumac-t-shirt-bikini-green": "", // LuLumac t shirt bikini green ($31–$35)
  "lulumac-t-shirt-bikini-pink": "", // Lulumac t shirt bikini pink ($31–$35)
  "lulumac-t-shirt-butter-pink-stripe": "", // LuluMac t shirt butter/pink stripe ($31–$39)
  "lulumac-t-shirt-camo": "", // LuluMac t shirt camo ($35–$39)
  "lulumac-t-shirt-camo-mint": "", // LuluMac t shirt camo/mint ($31–$35)
  "lulumac-t-shirt-crimson-camo": "", // LuLuMac t shirt crimson/camo ($31–$35)
  "lulumac-t-shirt-crimson-polka-dot": "", // LuluMac t shirt crimson/polka dot ($31–$35)
  "lulumac-t-shirt-green-orange-stripe": "", // LuLuMac t shirt green/orange stripe ($31–$35)
  "lulumac-t-shirt-leopard-blue": "", // LuluMac t shirt leopard/blue ($31–$35)
  "lulumac-t-shirt-leopard-pink": "", // LuluMac t shirt leopard/pink ($31–$35)
  "lulumac-t-shirt-leopard-red": "", // LuluMac t shirt leopard/red ($31–$35)
  "lulumac-t-shirt-neon-pink-camo": "", // LuluMac t shirt neon pink/camo ($31–$35)
  "lulumac-t-shirt-purple-white-camo": "", // Lulumac t shirt purple/white camo ($31–$35)
  "lulumac-t-shirt-stars-stripes": "", // LuluMac t shirt stars & stripes ($31–$35)
  "lulumac-tank-alabama": "", // LuluMac tank Alabama ($29–$31)
  "lulumac-tank-bubblegum-white": "", // LuluMac tank bubblegum/white ($25)
  "lulumac-tank-hot-pink": "", // LuluMac tank hot pink ($29–$31)
  "lulumac-tank-hot-pink-white": "", // LuluMac tank hot pink/white ($25)
  "lulumac-tank-navy": "", // LuluMac tank navy ($29–$31)
  "lulumac-tank-navy-stripe": "", // Lulumac tank navy/stripe ($29–$31)
  "lulumac-tank-purple": "", // LuluMac tank purple ($29–$31)
  "lulumac-tank-red-pink-stripe": "", // LuluMac tank red/pink stripe ($29–$31)
  "lulumac-tanks": "", // LuluMac tanks ($25–$31)
  "lulumac-waffle-pant-navy": "", // LuLuMac waffle pant navy ($49)
  "lulumac-waffle-pant-red": "", // LuluMac waffle pant red ($49)
  "lulumac-waffle-shorts": "", // LuLuMac waffle shorts ($29–$31)
  "lulumac-waffle-shorts-pink": "", // LuLuMac waffle shorts pink ($29)
  "lulumac-waffle-top": "", // LuluMac waffle top ($49–$51)
  "lulumac-waffle-top-pink": "", // LuLuMac waffle top pink ($49)
  "mid-rise-skort": "", // MID RISE SKORT ($40)
  "mustard-seed-white-summer-dress": "", // Mustard Seed white summer dress ($40)
  "papermoon-light-blue-set": "", // PaperMoon light blue set ($48)
  "parkside-t-shirt-lake-days": "", // PARKSIDE t shirt lake days ($30–$34)
  "pink-bow-pj-set": "", // Pink bow pj set ($35)
  "pink-western-pj-set": "", // Pink western pj set ($35)
  "purple-skort-set": "", // Purple skort set ($38)
  "rae-mode-french-terry-off-shoulder-top": "", // Rae Mode French Terry off shoulder top ($22)
  "she-sky-blue-v-neck-top": "", // SHE + SKY blue v neck top ($30)
  "she-sky-lavender-printed-crop-top": "", // SHE + SKY lavender printed crop top ($30)
  "she-sky-pink-silver-bow-top": "", // SHE + SKY pink silver bow top ($30)
  "she-sky-shorts": "", // SHE + SKY shorts ($32)
  "she-sky-smocked-swiss-dot-crop-top": "", // SHE + SKY smocked Swiss dot crop top ($32)
  "she-sky-thermal-knit-long-sleeve": "", // SHE + SKY thermal knit long sleeve ($30)
  "she-sky-black-button-down": "", // She+sky black button down ($34)
  "she-sky-black-top": "", // She+sky black top ($34)
  "she-sky-rib-knit-long-sleeve-salmon": "", // She+sky rib knit long sleeve salmon ($34)
  "she-sky-ruched-top-mauve": "", // She+sky ruched top mauve ($28)
  "short-set-leopard-detail-trim": "", // Short set leopard detail trim ($48)
  "southern-limit-black-short-sleeve": "", // Southern Limit black short sleeve ($49)
  "southern-limit-pullover-hoodie-black": "", // Southern Limit pullover hoodie black ($39–$41)
  "southern-limit-pullover-zip-black-camo": "", // Southern Limit pullover zip black camo ($49–$51)
  "southern-limit-pullover-zip-light-camo": "", // Southern Limit pullover zip light camo ($49–$51)
  "southern-limit-t-shirt": "", // Southern Limit t shirt ($36)
  "southern-limit-t-shirt-bottle-cap": "", // Southern Limit t shirt bottle cap ($26–$30)
  "southern-limit-t-shirt-cross": "", // Southern Limit t shirt cross ($26)
  "southern-limit-t-shirt-fish": "", // Southern Limit t shirt fish ($24)
  "southern-limit-t-shirt-flag": "", // Southern Limit t shirt flag ($26)
  "southern-limit-t-shirt-jeep": "", // Southern Limit t shirt jeep ($26–$30)
  "southern-limit-t-shirt-lab": "", // Southern limit t shirt lab ($24)
  "southern-limits-t-shirt-iron-sharpens-iron": "", // Southern Limits t shirt Iron sharpens Iron ($22–$24)
  "southern-proper-t-shirt": "", // Southern Proper T shirt ($36–$39.5)
  "southern-proper-t-shirt-2": "", // Southern Proper t shirt ($36)
  "striped-short-sleeve-top-and-shorts-casual-lounge-set": "", // Striped Short Sleeve Top and Shorts Casual Lounge Set ($35)
  "tcec-lilac-dress": "", // TCEC Lilac dress ($60)
  "tcec-orange-print-dress": "", // TCEC Orange print dress ($60)
  "tcec-pale-pink-blush-dress": "", // TCEC Pale pink blush dress ($49)
  "textured-contrast-trim-round-neck-t-shirt": "", // Textured Contrast Trim Round Neck T Shirt ($30)
  "twist-knit-jumpsuit-casual-overalls": "", // Twist Knit Jumpsuit Casual Overalls ($35)
  "usa-ribbed-graphic-tee-loose-fit-flag-day-july-4th": "", // USA Ribbed Graphic Tee Loose Fit Flag Day July 4th ($28)
  "vintage-bull-head-tee": "", // Vintage bull head tee ($15)
  "white-flounce-top": "", // White flounce top ($18)
  "white-leopard-shorts": "", // White leopard shorts ($15)
  "wholesalesir-bra-tank-black": "", // Wholesalesir bra tank black ($25–$28)
  "wholesalesir-bra-tank-green": "", // Wholesalesir bra tank green ($25–$28)
  "wishlist-blue-white-collar-dress": "", // Wishlist blue/white collar dress ($55)
  "wishlist-pink-summer-sweater": "", // Wishlist pink summer sweater ($40)
  "wishlist-yellow-summer-sweater": "", // Wishlist yellow summer sweater ($40)
  "zenana-ash-jade-top-with-pockets": "", // Zenana Ash jade top with pockets ($28)
  "zenana-brown-long-sleeve-raw-hem-top": "", // Zenana Brown long sleeve raw hem top ($18)
  "zenana-gray-solid-sweatshirt": "", // Zenana Gray solid sweatshirt ($20)
  "zenana-green-raw-hem-top": "", // Zenana Green raw hem top ($20)
  "zenana-hunter-green-long-sleeve-raw-hem-top": "", // Zenana Hunter green long sleeve raw hem top ($18)
  "zenana-jeans-reg": "", // Zenana Jeans reg ($36–$38)
  "zenana-jeans-skinny": "", // Zenana Jeans skinny ($34)
  "zenana-tan-pants": "", // Zenana Tan pants ($32)
  "color-drip": "", // Color Drip ($70)
  "dc-beyond-the-beach-12-25-oz": "", // DC Beyond the Beach 12.25 oz ($86)
  "dc-black-velvet": "", // DC Black Velvet ($65)
  "dc-dark-af-12-25-oz": "", // DC Dark AF 12.25 oz ($65)
  "dc-hard-feelings": "", // DC Hard Feelings ($75)
  "dc-juicy-details-12-25-oz": "", // DC Juicy Details 12.25 oz ($65)
  "dc-sun-honey": "", // DC Sun Honey ($55)
  "dc-sunshine-superstar": "", // DC SunShine Superstar ($60)
  "designer-skin-wavelength": "", // Designer Skin Wavelength ($95)
  "ds-bombshell-tingle": "", // DS Bombshell tingle ($55)
  "fuel-my-fire": "", // Fuel my fire ($65)
  "hemp-nation-tan-extender": "", // Hemp Nation tan extender ($22)
  "hempz-moisturizer": "", // Hempz moisturizer ($25)
  "honeymoon": "", // Honeymoon ($68)
  "infatuated": "", // Infatuated ($70)
  "jwow-ultra-dark": "", // Jwow ultra dark ($75)
  "jwoww-shore-win": "", // JWOWW Shore Win ($70)
  "peepers-eye-protection": "", // Peepers eye protection ($3)
  "sample-discount-pack": "", // Sample discount pack ($4)
  "sample-pack": "", // Sample pack ($7)
  "snooki-100x-extreme-blackout": "", // Snooki 100x Extreme Blackout ($70)
};
document.querySelectorAll('[data-sku]').forEach(btn=>{
  const url=PAYMENT_LINKS[btn.dataset.sku];
  if(url){btn.href=url;btn.target='_blank';btn.rel='noopener';}
  else{btn.addEventListener('click',e=>{e.preventDefault();alert('Online checkout for this item is coming soon!\n\nCall (205) 462-2115 or visit us at 2337 University Blvd E to purchase today.');});}
});
// ---------- catalog filter + search ----------
const grid=document.getElementById('pGrid');
if(grid){
  const cards=[...grid.querySelectorAll('.p-card')];
  const btns=[...document.querySelectorAll('.filter-btn')];
  const search=document.getElementById('pSearch');
  const count=document.getElementById('pCount');
  let cat='all';
  function apply(){
    const q=(search.value||'').toLowerCase().trim();
    let n=0;
    cards.forEach(c=>{
      const ok=(cat==='all'||c.dataset.cat===cat)&&(!q||c.dataset.name.includes(q));
      c.style.display=ok?'':'none';
      if(ok)n++;
    });
    count.textContent=n+' item'+(n===1?'':'s');
  }
  btns.forEach(b=>b.addEventListener('click',()=>{btns.forEach(x=>x.classList.remove('on'));b.classList.add('on');cat=b.dataset.filter;apply();}));
  search.addEventListener('input',apply);
  apply();
}